name: Trigger Cloud Run Download

on:
  push:
    branches:
      - main

jobs:
  trigger-download:
    runs-on: ubuntu-latest

    steps:
    - name: Send HTTP request to Cloud Run
      run: |
        curl -X GET https://cloudrun-998441420547.us-central1.run.app/download_data
